# Generated by Django 3.2.9 on 2021-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=50)),
                ('naver_grade', models.FloatField(null=True)),
                ('color', models.CharField(max_length=50)),
                ('color_R', models.CharField(max_length=50)),
                ('color_G', models.CharField(max_length=50)),
                ('color_B', models.CharField(max_length=50)),
                ('color_url', models.TextField(null=True)),
                ('release_date', models.TextField()),
            ],
        ),
    ]
