# Generated by Django 3.2.9 on 2021-11-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='color',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='color_B',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='color_G',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='color_R',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='color_url',
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('color_url', models.TextField(null=True)),
                ('color_1_R', models.CharField(max_length=50)),
                ('color_1_G', models.CharField(max_length=50)),
                ('color_1_B', models.CharField(max_length=50)),
                ('color_2_R', models.CharField(max_length=50)),
                ('color_2_G', models.CharField(max_length=50)),
                ('color_2_B', models.CharField(max_length=50)),
                ('color_3_R', models.CharField(max_length=50)),
                ('color_3_G', models.CharField(max_length=50)),
                ('color_3_B', models.CharField(max_length=50)),
                ('color_4_R', models.CharField(max_length=50)),
                ('color_4_G', models.CharField(max_length=50)),
                ('color_4_B', models.CharField(max_length=50)),
                ('color_5_R', models.CharField(max_length=50)),
                ('color_5_G', models.CharField(max_length=50)),
                ('color_5_B', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='color')),
            ],
        ),
    ]
