# Generated by Django 3.2.9 on 2021-11-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_usercolorrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
