# Generated by Django 3.2.9 on 2021-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='draw',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
